name: Manual Script Runner

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        run: bash ./health-check.sh
